<a href="https://colab.research.google.com/github/armaanrathod/EDA-lab-3rd-sem-final/blob/main/exp2_28.07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import pandas as pd
from google.colab import files
import io

uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}"')
  try:
    restaurant_df_local = pd.read_csv(io.StringIO(uploaded[fn].decode('utf-8')))
    print(f"'{fn}' loaded successfully!")
    display(restaurant_df_local.head())
  except Exception as e:
    print(f"Error reading '{fn}': {e}")

Please select your 'restraunt.csv' file from your local system to upload:

Saving restaurants.csv to restaurants (1).csv
User uploaded file "restaurants (1).csv"
'restaurants (1).csv' loaded successfully!

,Restaurant_ID,Name,City,State,Country,Zip_Code,Latitude,Longitude,Alcohol_Service,Smoking_Allowed,Price,Franchise,Area,Parking
0,132560,Puesto de Gorditas,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.752304,-99.166913,NaN,Yes,Low,No,Open,Public
1,132561,Cafe Ambar,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.726819,-99.126506,NaN,No,Low,No,Closed,NaN
2,132564,Church's,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.730925,-99.145185,NaN,No,Low,No,Closed,NaN
3,132572,Cafe Chaires,San Luis Potosi,San Luis Potosi,Mexico,NaN,22.141647,-100.992712,NaN,No,Low,No,Closed,Yes
4,132583,McDonalds Centro,Cuernavaca,Morelos,Mexico,62000.0,18.922290,-99.234332,NaN,No,Low,Yes,Closed,NaN

In [47]:
df.isnull().sum()

Restaurant_ID       0
Name                0
City                0
State               0
Country             0
Zip_Code           74
Latitude            0
Longitude           0
Alcohol_Service    87
Smoking_Allowed     0
Price               0
Franchise           0
Area                0
Parking            65
dtype: int64

In [44]:
df.isnull().sum().sum()

np.int64(226)

In [45]:
df.count()

Restaurant_ID      130
Name               130
City               130
State              130
Country            130
Zip_Code            56
Latitude           130
Longitude          130
Alcohol_Service     43
Smoking_Allowed    130
Price              130
Franchise          130
Area               130
Parking             65
dtype: int64

In [46]:
df.Zip_Code.dropna()

4      62000.0
22     87018.0
29     62320.0
31     78280.0
33     78349.0
50     78433.0
61     62250.0
63     62290.0
67     62790.0
68     62170.0
74     62290.0
76     78250.0
80     78000.0
81     78399.0
82     78210.0
83     78210.0
84     78000.0
85     79300.0
86     74000.0
88     78269.0
90     78240.0
91     78000.0
92     78200.0
93     78310.0
94     78269.0
95     78214.0
96     78430.0
97     78000.0
98     78000.0
99     62460.0
100    78000.0
101    78270.0
102    78390.0
103    64000.0
104    78250.0
105    78310.0
106    78000.0
107    78000.0
108    78740.0
109    78250.0
110    78038.0
111    78399.0
112    78421.0
113    78396.0
114    78220.0
115    78000.0
116    78000.0
117    78269.0
118    78395.0
119    78000.0
120    78270.0
121    78000.0
122    78421.0
123    78000.0
124    78290.0
127    78000.0
Name: Zip_Code, dtype: float64

In [48]:
filledDf = df.fillna(0)
filledDf

,Restaurant_ID,Name,City,State,Country,Zip_Code,Latitude,Longitude,Alcohol_Service,Smoking_Allowed,Price,Franchise,Area,Parking
0,132560,Puesto de Gorditas,Ciudad Victoria,Tamaulipas,Mexico,0.0,23.752304,-99.166913,0,Yes,Low,No,Open,Public
1,132561,Cafe Ambar,Ciudad Victoria,Tamaulipas,Mexico,0.0,23.726819,-99.126506,0,No,Low,No,Closed,0
2,132564,Church's,Ciudad Victoria,Tamaulipas,Mexico,0.0,23.730925,-99.145185,0,No,Low,No,Closed,0
3,132572,Cafe Chaires,San Luis Potosi,San Luis Potosi,Mexico,0.0,22.141647,-100.992712,0,No,Low,No,Closed,Yes
4,132583,McDonalds Centro,Cuernavaca,Morelos,Mexico,62000.0,18.922290,-99.234332,0,No,Low,Yes,Closed,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,135088,Cafeteria Cenidet,Cuernavaca,Morelos,Mexico,0.0,18.876011,-99.219890,0,No,Low,No,Closed,Public
126,135104,Vips,Ciudad Victoria,Tamaulipas,Mexico,0.0,23.752982,-99.168434,Full Bar,No,Medium,Yes,Closed,Yes
127,135106,El Rincón De San Francisco,San Luis Potosi,San Luis Potosi,Mexico,78000.0,22.149709,-100.976093,Wine & Beer,Bar Only,Medium,No,Open,0
128,135108,Potzocalli,San Luis Potosi,San Luis Potosi,Mexico,0.0,22.136253,-100.933585,0,No,Low,No,Closed,0
129,135109,Paniroles,Cuernavaca,Morelos,Mexico,0.0,18.921785,-99.235350,Wine & Beer,No,Medium,No,Closed,0